apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Alertmanager
    type: alertmanager
    access: proxy
    isDefault: true
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus

  - name: Loki
    type: loki
    access: proxy
    jsonData:
      maxLines: 1000
    basicAuth: false
    url: http://loki:3100
    isDefault: false
    editable: true