version: '3.8'
services:
  app:
    image: devops-it.mephi.ru/alumniclub/app:latest
    env_file:
      - "../env/.env"
      - "../env/.prod.env"

  broadcast-service:
    image: devops-it.mephi.ru/alumniclub/broadcast-service:latest
    env_file:
      - "../env/.env"
      - "../env/.prod.env"

  image-service:
    image: devops-it.mephi.ru/alumniclub/image-service:latest
    env_file:
      - "../env/.env"
      - "../env/.prod.env"

  recommendation-service:
    image: devops-it.mephi.ru/alumniclub/recommendation-service:latest
    env_file:
      - "../env/.env"
      - "../env/.prod.env"

  mysql:
    image: mysql:latest
    env_file:
      - "../env/.env"
      - "../env/.prod.env"
    volumes:
      - "../config/init/01.prod.sql:/docker-entrypoint-initdb.d/01.sql"
      - "../data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"

  promtail:
    build:
      context: .
      dockerfile: ../docker-common/runPromtail.Dockerfile
    env_file:
      - "../env/.env"
      - "../env/.prod.env"

  postfix:
    image: marvambass/versatile-postfix:latest
    command:
      - alumniclub.mephi.ru
      - no-reply:@TC4WUxXuzvduMGmz
    ports:
      - "25:25"
    volumes:
      - ../data/postfix/spool:/var/spool/postfix
      - ../data/postfix/log:/var/log
      - ../data/postfix/keys/private.pem:/etc/postfix/dkim/dkim.key
    restart: always