server:
  port: ${IMAGE_SERVICE_PORT:8084}
  forward-headers-strategy: framework
  servlet:
    context-path: /image-service

# Spring

spring:
  application:
    name: image-service

  profiles:
    active: dev

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:password}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:AlumniClubDev}
    username: ${MARIADB_USER:admin}
    password: ${MARIADB_PASSWORD:password}

  jpa:
    show-sql: true
    format-sql: true
    generate-ddl: off
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none

# Actuator

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

# Logging

logging:
  file.name: "image-service"
  path.main: "./logs"
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
    console: "[%boldWhite(%d{YYYY-MM-dd HH:mm:ss.SSS})] [%X{userId} %X{requestId}] [%thread] %cyan(%-5level) %yellow(%logger{36}) - %msg%n"
  level:
    root: INFO

storage:
  image:
    criticalSize: 1MB
    maxSizeUser: 5MB
    maxSizeAdmin: 15MB
    maxStoredSize: 3MB