# Prod Profile Docker

debug: false

# Spring

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:AlumniClub}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:password}

  cache:
    type: redis

  jpa:
    show-sql: false
    generate-ddl: off
    hibernate:
      ddl-auto: update # TODO none
    properties:
      hibernate:
        show_sql: false

# RabbitMQ

rabbitmq:
  host: ${RABBIT_HOST:localhost}
  port: ${RABBIT_PORT:5672}
  username: ${RABBITMQ_DEFAULT_USER:admin}
  password: ${RABBITMQ_DEFAULT_PASS:password}
  replyTimeout: 60000

# API Documentation

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Custom Properties

feature-toggle:
  features:
    verifyEmail: true