# Test Profile

debug: true

# Spring

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_TEST:localhost}:${DB_PORT_TEST:3307}/${DB_NAME_TEST:AlumniClubTest}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:password}

  jpa:
    show-sql: true
    format-sql: true
    generate-ddl: false
    hibernate:
      show_sql: true
      ddl-auto: create-drop

  cache:
    type: none

# Custom Properties

feature-toggle:
  featureState:
    registration: true
    verifyEmail: true
    sendForms: true
